version: "3"

services:
  node:
    container_name: nodeapp
    image: node:14
    restart: always
    ports:
      - "5000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongodatabase
    image: mongo
    ports: 
      - "27018:27017"
